### ISSUE TITLE
Upload feature 

### ISSUE THREAD

**Issue by gabi-gabs** [HumanRightsWatch/VHS#19]
VHS users can upload photos and videos directly to their Collections

**Comment by gabi-gabs** [comment]
This would include an 'upload' button, where users could upload content directly from their desktop to a Collection

**Comment by U039b** [comment]
I have implemented this feature but it is not deployed since I was waiting for your feedback. The UI looks like:
![image](https://user-images.githubusercontent.com/34188010/163356016-25c75dd6-ea87-4657-b279-e3f6ef808e84.png)

**Comment by U039b** [comment]
Changed *Origin* to *Description*

![image](https://user-images.githubusercontent.com/34188010/163631931-fb46eeb0-e758-4825-bd19-03ce82ac7e54.png)
