### ISSUE TITLE
Remove about page and link to Gnosis on the front page 

### ISSUE THREAD

**Issue by gabi-gabs** [HumanRightsWatch/VHS#22]

**Comment by gabi-gabs** [comment]
Esther - can you change this sentence to the sentence below 

From this - "Click on the About section in the menu above to learn more about the tool and for frequently asked questions."

To this - "See this [page on Gnosis](https://gnosis.hrw.org/how-to-use-vhs/) to learn more about the tool and for frequently asked questions."

**Comment by gabi-gabs** [comment]
Could you also add 'and photographs' to the description.

Welcome to VHS. This tool will help you to download videos AND PHOTOGRAPHS from over 1000 websites including social media platforms. Click on the About section in the menu above to learn more about the tool and for frequently asked questions.

Thank you!

**Comment by U039b** [comment]
Regression

**Comment by gabi-gabs** [comment]
Thanks Esther - is the issue with the way that VHS and Gnosis talks to each other? Is there an easy fix to this, if not - maybe we can just include the link that people have to copy and paste - https://gnosis.hrw.org/how-to-use-vhs/

**Comment by U039b** [comment]
This issue should be fixed in the version I deployed on your side, could you please confirm?
