### ISSUE TITLE
Add a metadata viewing tool - Exiftool 

### ISSUE THREAD

**Issue by gabi-gabs** [HumanRightsWatch/VHS#24]

**Comment by U039b** [comment]
I will integrate https://github.com/sylikc/pyexiftool

**Comment by U039b** [comment]
I have integrated *Exiftool* and revamped the UI a bit.
![image](https://user-images.githubusercontent.com/34188010/163631517-9a709c4c-8d0e-4d3e-9492-5bccb1679d84.png)
![image](https://user-images.githubusercontent.com/34188010/163631646-b9a3e1df-0fe9-4f43-8770-94ab2c9d43df.png)

**Comment by gabi-gabs** [comment]
This is really great - thank you!
