### ISSUE TITLE
Downloading full collections not just separate videos 

### ISSUE THREAD

**Issue by gabi-gabs** [HumanRightsWatch/VHS#25]
Option for users to:
- Download collections in their entirety. 

When they do, all the videos from the collection are saved in a separate folder named All_Videos.

**Comment by U039b** [comment]
Is it okay if downloading an entire collection is possible *iff* the given collection is closed? If not, we would have to discuss more on this issue :)

**Comment by gabi-gabs** [comment]
It would be better if users could download whole archives that were still 'open' - as we will often download many of these videos to analyse them locally and then continue to add to the Collection. But if it's hard to implement then users can still click on the separate videos to download them.
