### ISSUE TITLE
Adding distressing content tags to the videos 

### ISSUE THREAD

**Issue by gabi-gabs** [HumanRightsWatch/VHS#27]
Tag: Distressing content 

Ideally a drop down menu:
- Shows children in distress
- Shows bodies 
-

**Comment by U039b** [comment]
Do you have a comprehensive list of tags I can integrate?

**Comment by gabi-gabs** [comment]
I imagined it could be text fields, where users could add their own tags to their Collections rather than choosing from a drop down. Would that be possible?

**Comment by gabi-gabs** [comment]
Great - could it be possible to have these tags open text fields for Collections and also individual videos?
