### ISSUE TITLE
Blur filter on the photos and videos 

### ISSUE THREAD

**Issue by gabi-gabs** [HumanRightsWatch/VHS#28]
I think I've seen one already on VHS, if so - this looks great! Ideally all the photos and videos would have the blur filter on them and when the users put their mouse over them then the image still becomes visible.

**Comment by U039b** [comment]
This feature is already deployed. Thumbnails are blurred, the blur is removed when the mouse's cursor is over a thumdnail.

![image](https://user-images.githubusercontent.com/34188010/163355504-4b450ed3-3622-4e4d-850b-7948e7983c28.png)

**Comment by U039b** [comment]
If you consider that this feature is correctly implemented, feel free to close this issue :)
