### ISSUE TITLE
Automatically determine the type of download request

### ISSUE THREAD

**Issue by U039b** [HumanRightsWatch/VHS#31]
Since we introduced the possibility to download photographs in addition to videos, VHS would have to automatically determine if it has to use either youtube-dl or gallery-dl to handle the request. In the case of a given URL can be handled by both backends, VHS will run both of them. This way, both photographs and videos would be automatically downloaded from a given URL.

@gabi-gabs feel free to add your feedback and thoughts about this issue.

**Comment by U039b** [comment]
By default, VHS will try to determine if it has to use YoutubeDL or GalleryDL. 

![image](https://user-images.githubusercontent.com/34188010/163631776-a60167cc-ee61-4e14-bfed-f8923e006f66.png)

**Comment by gabi-gabs** [comment]
Thank you Esther - would it be possible to then remove the 'Type*' drop down field as this is now happening in the background the user doesn't have to select anything? Or should we keep this if there is a problem with VHS detecting the type of media so we can manually select it?
