### ISSUE TITLE
Revamp notification management

### ISSUE THREAD

**Issue by U039b** [HumanRightsWatch/VHS#32]
Notification management is shitty, notifications are not usable at all. We have to fix it!

**Comment by gabi-gabs** [comment]
I just added this to another comment that I've now closed when seeing this - 

When you click on 'notifications' you can't then click off it again and have to refresh the page to get rid of the view. Also my notifications don't seem to be updating.

**Comment by U039b** [comment]
Yes, I have to revamp the notification system. Right now it is just shitty as hell.

**Comment by gabi-gabs** [comment]
Lol as shitty as hell - I will start using that phrase more
