### ISSUE TITLE
Ability to delete videos uploaded or downloaded

### ISSUE THREAD

**Issue by gabi-gabs** [HumanRightsWatch/VHS#35]
Hi Esther, 

Could you add an option for users to delete individual videos/ photos they might have accidentally added to a Collection and want to remove? 

Thanks
Gabi

**Comment by U039b** [comment]
Sure! Can you tell more about traceability implications?

**Comment by gabi-gabs** [comment]
Sorry I missed this comment... good question. Could we save this video or photograph in the log and keep a record that it has been deleted and not delete it from the server but delete it from the user's Collection? If that's not too much work? 

In addition to having a delete function, could we also have an 'Undo' function, so if they accidentally delete a video, archive a collection, etc could there could be an Undo feature?

**Comment by U039b** [comment]
What about just hidding the content of a given download request? We can label the button "Delete"/"Recover" but the action is just to hide/show it from the list of download contents.

**Comment by gabi-gabs** [comment]
Yes, that would work well!

**Comment by U039b** [comment]
Should be fixed now.
