### ISSUE TITLE
Telegram downloading group videos in a playlist

### ISSUE THREAD

**Issue by gabi-gabs** [HumanRightsWatch/VHS#64]
This could be an issue with Telegram, but when you try and download a group of videos in one post, it only downloads the first one.

**Comment by U039b** [comment]
Hi!
Can you please give me one or to URLs I can test with?

**Comment by gabi-gabs** [comment]
Here is a URL example - https://t.me/Qaraqalpaq_bugin2022/251

**Comment by U039b** [comment]
Unfortunately, this feature is not supported by the download backends we use. User has to request the download of each video separately.
