### ISSUE TITLE
Upload file size 

### ISSUE THREAD

**Issue by gabi-gabs** [HumanRightsWatch/VHS#65]
If the upload file size could be expanded further, I tried to upload a video that was 8.9 MB and it timed out.

**Comment by U039b** [comment]
Does this error occur under specific conditions such as slow network connection? I see that you were able to upload a 22,6 MB file. During some tests on your instance, I was able to upload few large files (>400MB).

**Comment by gabi-gabs** [comment]
This has been resolved, it was not a 8.9 MB file but much larger :)
